# Generated by Django 5.0.7 on 2024-08-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auth_Clubs',
            new_name='Auth_Club',
        ),
    ]
