# Generated by Django 5.0.7 on 2024-08-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_notifications',
            field=models.BooleanField(default=True, verbose_name='알림 여부'),
        ),
    ]
