# Generated by Django 5.0.7 on 2024-08-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_user_is_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_notifications',
        ),
    ]
