# Generated by Django 5.0.7 on 2024-08-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scrap',
        ),
    ]
