# Generated by Django 5.0.7 on 2024-08-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_comment_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='동아리명'),
        ),
    ]
