<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-08-05 17:29
=======
# Generated by Django 5.0.7 on 2024-08-05 18:23
>>>>>>> bb54cd83893e541f6cec5f99bfb0f7c80d760c53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_club_club_name'),
        ('community', '0004_post_image'),
    ]

    operations = [
    ]
