
# Generated by Django 5.0.7 on 2024-08-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_club_club_name'),
        ('community', '0004_post_image'),
    ]

    operations = [
    ]
