# Generated by Django 5.0.7 on 2024-08-08 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_merge_0004_alter_club_club_name_0004_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='depth',
            field=models.IntegerField(default=0, verbose_name='댓글 깊이'),
        ),
        migrations.AddField(
            model_name='comment',
            name='liked',
            field=models.IntegerField(default=0, verbose_name='좋아요 개수'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.IntegerField(default=0, verbose_name='좋아요 개수'),
        ),
        migrations.AddField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='게시글 고정 여부'),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_name',
            field=models.CharField(max_length=255, verbose_name='동아리명'),
        ),
    ]
