# Generated by Django 5.0.7 on 2024-08-05 17:47

import apps.community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_merge_0004_alter_club_club_name_0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.community.models.user_directory_path),
        ),
    ]
