# Generated by Django 5.0.7 on 2024-08-09 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_comment_depth_comment_liked_comment_parent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='club_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='community.club'),
            preserve_default=False,
        ),
    ]
