# Generated by Django 5.0.7 on 2024-08-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_post_club_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_name',
            field=models.CharField(max_length=255, verbose_name='게시판 이름'),
        ),
    ]
