# Generated by Django 5.0.7 on 2024-08-11 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_remove_post_liked_post_liked_by_scrap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scrap',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='scrap',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.post'),
        ),
        migrations.AddField(
            model_name='scrap',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='post',
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='user',
        ),
    ]
