# Generated by Django 5.0.7 on 2024-08-11 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_alter_scrap_post_id_alter_scrap_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scraped_by',
            field=models.ManyToManyField(related_name='scraped_posts', through='community.Scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='community.post'),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='scrap',
            unique_together={('user_id', 'post_id')},
        ),
    ]
