# Generated by Django 5.0.7 on 2024-08-11 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_post_scraped_by_alter_scrap_post_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='scraped_by',
        ),
    ]
