# Generated by Django 5.0.7 on 2024-08-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_remove_post_scraped_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scrap',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='user_id',
        ),
    ]
