# Generated by Django 5.0.7 on 2024-08-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_post_scraped_by_delete_scrap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='동아리명'),
        ),
    ]
