# Generated by Django 5.0.7 on 2024-08-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_alter_club_club_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='scrap_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
