# Generated by Django 5.0.7 on 2024-08-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_post_liked_cnt_post_scrap_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_intro',
            field=models.CharField(default='', max_length=255, verbose_name='동아리 소개'),
        ),
    ]
