# Generated by Django 5.0.7 on 2024-08-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_post_liked_cnt_post_scrap_cnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='club_intro',
        ),
    ]
