# Generated by Django 5.0.7 on 2024-08-16 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_alter_club_club_intro'),
        ('community', '0018_remove_club_club_intro'),
    ]

    operations = [
    ]
